# Site settings
title: "acdcjunior's"
email: acdcjunior@gmail.com
description: "Random thoughts on software and..."
baseurl: ""
url: "http://acdcjunior.github.io/"
title_description: "Title description long."
title_image: "http://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-50217609-2"
disqus_account: acdcjunior
github_repository: https://github.com/acdcjunior/acdcjunior.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: acdcjunior
github_username:  acdcjunior
# linkedin_link: http://example.com/
google_plus_link: https://www.google.com/+acdcjunior
stackoverflow_link: http://stackoverflow.com/users/1850609/acdcjunior

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/acdcjunior\">Antônio \"acdc\" Jr.</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/acdcjunior/acdcjunior.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
# permalink: pretty
exclude: [vendor]

excerpt_separator: <!--more-->
timezone: America/Sao_Paulo
markdown: kramdown
permalink: /:title.html




# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

#paginate: 10 # pagination based on number of posts
#paginate_path: "page:num"
#exclude: ["README.md"] # files to exclude
#pygments: true
#
#title: acdcjunior's
#description: descriz
#author:
#  name: acdcjunior
##  email:
#  github: acdcjunior
#  twitter: acdcjunior
##  pinterest: aaaaaaaa
##  linkedin: aaaaaaaa
#  bio: obvious questions, necessary answers.
#  email_md5: 3a07af5b5bd64cf027735db364a14298
#
#rss_path: feed.xml
#categories_path: categories.html
#tags_path: tags.html
#encoding: utf-8

# BASE_PATH:

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"


